[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
#requires = ["setuptools>=61.0"]
#build-backend = "setuptools.build_meta"

[project]
name = "pymtbl"
version = "0.5.1"
authors = [
  { name="DomainTools LLC", email="mcrawford@domaintools.com" },
]
description = "Python extension module for the mtbl C library"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/farsightsec/pymtbl"
